### ISSUE TITLE
Could you give some explanation about output?

### ISSUE THREAD

**Issue by mrsempress** [prclibo/kitti_eval#19]
First, thanks for your work. As a beginner, I don't know what is the output represent.
There are four txt for each class and related '.gp', I don't know the number in each row. 
Could you give me some explanation or give me some Tutorials? Thanks.

**Comment by mrsempress** [comment]
I also get warning like that
![image](https://user-images.githubusercontent.com/31315255/110725621-dbb60380-8252-11eb-9b65-678a370f2634.png)
And all the produced pdfs are empty.

**Comment by Wyx9352** [comment]
Have you solved it yet? I'm also curious to know what it means
